# Generated by Django 5.2.11 on 2026-02-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotfaq',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords to trigger this answer', max_length=255),
        ),
    ]
