# Generated by Django 5.2.11 on 2026-02-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotfaq_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotfaq',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords to match user questions', max_length=255, null=True),
        ),
    ]
