# Generated by Django 5.2.11 on 2026-02-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Required for staff users', max_length=100, null=True),
        ),
    ]
