# Generated by Django 5.2.11 on 2026-02-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_rename_student_complaint_user_alter_complaint_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
