# Generated by Django 5.2.11 on 2026-02-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_category_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
    ]
