# Generated by Django 5.2.11 on 2026-02-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_category_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='building_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='course_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='dorm_block',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
